/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AbcCheckbox {
    }
    interface AbcInput {
    }
}
declare global {
    interface HTMLAbcCheckboxElement extends Components.AbcCheckbox, HTMLStencilElement {
    }
    var HTMLAbcCheckboxElement: {
        prototype: HTMLAbcCheckboxElement;
        new (): HTMLAbcCheckboxElement;
    };
    interface HTMLAbcInputElement extends Components.AbcInput, HTMLStencilElement {
    }
    var HTMLAbcInputElement: {
        prototype: HTMLAbcInputElement;
        new (): HTMLAbcInputElement;
    };
    interface HTMLElementTagNameMap {
        "abc-checkbox": HTMLAbcCheckboxElement;
        "abc-input": HTMLAbcInputElement;
    }
}
declare namespace LocalJSX {
    interface AbcCheckbox {
    }
    interface AbcInput {
    }
    interface IntrinsicElements {
        "abc-checkbox": AbcCheckbox;
        "abc-input": AbcInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "abc-checkbox": LocalJSX.AbcCheckbox & JSXBase.HTMLAttributes<HTMLAbcCheckboxElement>;
            "abc-input": LocalJSX.AbcInput & JSXBase.HTMLAttributes<HTMLAbcInputElement>;
        }
    }
}
