/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AbcInput {
        "ariaLabel": string;
        "disabled": boolean;
    }
}
declare global {
    interface HTMLAbcInputElement extends Components.AbcInput, HTMLStencilElement {
    }
    var HTMLAbcInputElement: {
        prototype: HTMLAbcInputElement;
        new (): HTMLAbcInputElement;
    };
    interface HTMLElementTagNameMap {
        "abc-input": HTMLAbcInputElement;
    }
}
declare namespace LocalJSX {
    interface AbcInput {
        "ariaLabel"?: string;
        "disabled"?: boolean;
    }
    interface IntrinsicElements {
        "abc-input": AbcInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "abc-input": LocalJSX.AbcInput & JSXBase.HTMLAttributes<HTMLAbcInputElement>;
        }
    }
}
